# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_date', models.DateField()),
                ('end_date', models.DateField()),
                ('str_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_size', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_official', models.CharField(max_length=50)),
                ('name_branding', models.CharField(max_length=50)),
                ('header', models.CharField(max_length=200)),
                ('intro1', models.CharField(max_length=200)),
                ('intro2', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=50)),
                ('img_src1', models.CharField(max_length=50)),
                ('img_txt1', models.CharField(max_length=100)),
                ('img_src2', models.CharField(max_length=50)),
                ('img_txt2', models.CharField(max_length=100)),
                ('img_src3', models.CharField(max_length=50)),
                ('img_txt3', models.CharField(max_length=100)),
                ('img_src4', models.CharField(max_length=50)),
                ('img_txt4', models.CharField(max_length=100)),
                ('key_online', models.BooleanField(default=False)),
                ('key_credit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramEligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osr.Eligibility')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osr.Program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osr.Outcome')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osr.Program')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img_src', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address_street', models.CharField(max_length=50)),
                ('address_city', models.CharField(max_length=30)),
                ('address_province', models.CharField(max_length=30)),
                ('address_zipcode', models.CharField(max_length=30)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lon', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='offering',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osr.Program'),
        ),
        migrations.AddField(
            model_name='offering',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osr.ServiceProvider'),
        ),
        migrations.AddField(
            model_name='offering',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osr.Stream'),
        ),
    ]
