# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'eligibilities',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_date', models.DateField(verbose_name=b'Start date')),
                ('end_date', models.DateField(verbose_name=b'End date')),
                ('class_size', models.CharField(choices=[(b'01', b'1 - 10'), (b'02', b'11 - 20'), (b'03', b'20+')], max_length=2)),
                ('learning_style', models.CharField(choices=[(b'ON', b'Online'), (b'IN', b'In-person'), (b'BL', b'Blended')], max_length=2)),
                ('clb_01', models.BooleanField(default=False, verbose_name=b'CLB level 1')),
                ('clb_02', models.BooleanField(default=False, verbose_name=b'CLB level 2')),
                ('clb_03', models.BooleanField(default=False, verbose_name=b'CLB level 3')),
                ('clb_04', models.BooleanField(default=False, verbose_name=b'CLB level 4')),
                ('clb_05', models.BooleanField(default=False, verbose_name=b'CLB level 5')),
                ('clb_06', models.BooleanField(default=False, verbose_name=b'CLB level 6')),
                ('clb_07', models.BooleanField(default=False, verbose_name=b'CLB level 7')),
                ('clb_08', models.BooleanField(default=False, verbose_name=b'CLB level 8')),
                ('clb_09', models.BooleanField(default=False, verbose_name=b'CLB level 9')),
                ('clb_10', models.BooleanField(default=False, verbose_name=b'CLB level 10')),
                ('clb_11', models.BooleanField(default=False, verbose_name=b'CLB level 11')),
                ('clb_12', models.BooleanField(default=False, verbose_name=b'CLB level 12')),
            ],
        ),
        migrations.CreateModel(
            name='OfferingFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osr.Feature')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osr.Offering')),
            ],
        ),
        migrations.CreateModel(
            name='OfferingProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osr.Offering')),
            ],
        ),
        migrations.CreateModel(
            name='OfferingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.CharField(choices=[(b'Monday', b'Monday'), (b'Tuesday', b'Tuesday'), (b'Wednesday', b'Wednesday'), (b'Thursday', b'Thursday'), (b'Friday', b'Friday'), (b'Saturday', b'Saturday'), (b'Sunday', b'Sunday')], max_length=10)),
                ('str_time', models.TimeField(verbose_name=b'Start time')),
                ('end_time', models.TimeField(verbose_name=b'End time')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osr.Offering')),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('colour', models.CharField(default=b'#000000', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_official', models.CharField(max_length=50)),
                ('name_branding', models.CharField(max_length=50)),
                ('code', models.CharField(default=b'PRO', max_length=3)),
                ('header', models.CharField(blank=True, max_length=200)),
                ('intro1', models.TextField(blank=True, default=b'', max_length=200)),
                ('intro2', models.TextField(blank=True, default=b'', max_length=200)),
                ('video', models.CharField(blank=True, default=b'', max_length=50)),
                ('img_src1', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('img_txt1', models.CharField(blank=True, default=b'', max_length=100)),
                ('img_src2', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('img_txt2', models.CharField(blank=True, default=b'', max_length=100)),
                ('img_src3', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('img_txt3', models.CharField(blank=True, default=b'', max_length=100)),
                ('img_src4', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('img_txt4', models.CharField(blank=True, default=b'', max_length=100)),
                ('is_available_online', models.BooleanField(default=False)),
                ('offers_ossd_credits', models.BooleanField(default=False)),
                ('colour', models.CharField(default=b'#000000', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDeliverySite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('address_street', models.CharField(blank=True, max_length=50)),
                ('address_city', models.CharField(blank=True, max_length=30)),
                ('address_province', models.CharField(blank=True, max_length=30)),
                ('address_zipcode', models.CharField(blank=True, max_length=30)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lon', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('address_street', models.CharField(blank=True, max_length=50)),
                ('address_city', models.CharField(blank=True, max_length=30)),
                ('address_province', models.CharField(blank=True, max_length=30)),
                ('address_zipcode', models.CharField(blank=True, max_length=30)),
                ('programs', models.ManyToManyField(to='osr.Program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('programs', models.ManyToManyField(to='osr.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=12)),
                ('programs', models.ManyToManyField(to='osr.Program')),
            ],
        ),
        migrations.AddField(
            model_name='servicedeliverysite',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osr.ServiceProvider'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='programs',
            field=models.ManyToManyField(to='osr.Program'),
        ),
        migrations.AddField(
            model_name='offeringprofession',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osr.Profession'),
        ),
        migrations.AddField(
            model_name='offering',
            name='outcomes',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field=b'program', chained_model_field=b'programs', horizontal=True, to='osr.Outcome', verbose_name=b'outcomes'),
        ),
        migrations.AddField(
            model_name='offering',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osr.Program'),
        ),
        migrations.AddField(
            model_name='offering',
            name='requirements',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field=b'program', chained_model_field=b'programs', horizontal=True, to='osr.Eligibility', verbose_name=b'requirements'),
        ),
        migrations.AddField(
            model_name='offering',
            name='service_delivery_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osr.ServiceDeliverySite'),
        ),
        migrations.AddField(
            model_name='offering',
            name='streams',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field=b'program', chained_model_field=b'programs', horizontal=True, to='osr.Stream', verbose_name=b'streams'),
        ),
        migrations.AddField(
            model_name='offering',
            name='subjects',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field=b'program', chained_model_field=b'programs', horizontal=True, to='osr.Subject', verbose_name=b'subjects'),
        ),
        migrations.AddField(
            model_name='eligibility',
            name='programs',
            field=models.ManyToManyField(to='osr.Program'),
        ),
    ]
