# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eligibility',
            options={'verbose_name_plural': 'eligibilities'},
        ),
        migrations.RenameField(
            model_name='program',
            old_name='key_credit',
            new_name='is_available_online',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='key_online',
            new_name='offers_ossd_credits',
        ),
        migrations.AlterField(
            model_name='program',
            name='img_src1',
            field=models.ImageField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='program',
            name='img_src2',
            field=models.ImageField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='program',
            name='img_src3',
            field=models.ImageField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='program',
            name='img_src4',
            field=models.ImageField(upload_to=b''),
        ),
    ]
