# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0002_program_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmigrationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='text')),
                ('text_en', models.CharField(max_length=200, null=True, verbose_name='text')),
                ('text_fr', models.CharField(max_length=200, null=True, verbose_name='text')),
            ],
            options={
                'verbose_name': 'immigration status',
                'verbose_name_plural': 'immigration status',
            },
        ),
        migrations.CreateModel(
            name='LearningOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='text')),
                ('text_en', models.CharField(max_length=200, null=True, verbose_name='text')),
                ('text_fr', models.CharField(max_length=200, null=True, verbose_name='text')),
            ],
            options={
                'verbose_name': 'learning option',
                'verbose_name_plural': 'learning options',
            },
        ),
        migrations.CreateModel(
            name='ProgramLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='text')),
                ('text_en', models.CharField(max_length=150, null=True, verbose_name='text')),
                ('text_fr', models.CharField(max_length=150, null=True, verbose_name='text')),
                ('link', models.CharField(max_length=150, verbose_name='link')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'program link',
                'verbose_name_plural': 'program links',
            },
        ),
        migrations.CreateModel(
            name='ScheduleOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='text')),
                ('text_en', models.CharField(max_length=200, null=True, verbose_name='text')),
                ('text_fr', models.CharField(max_length=200, null=True, verbose_name='text')),
            ],
            options={
                'verbose_name': 'schedule option',
                'verbose_name_plural': 'schedule options',
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='text')),
                ('text_en', models.CharField(max_length=200, null=True, verbose_name='text')),
                ('text_fr', models.CharField(max_length=200, null=True, verbose_name='text')),
            ],
            options={
                'verbose_name': 'service provider type',
                'verbose_name_plural': 'service provider types',
            },
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, default=b'', max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description_en',
            field=models.TextField(blank=True, default=b'', max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description_fr',
            field=models.TextField(blank=True, default=b'', max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='program',
            name='details',
            field=models.TextField(blank=True, default=b'', max_length=1000, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='program',
            name='details_en',
            field=models.TextField(blank=True, default=b'', max_length=1000, null=True, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='program',
            name='details_fr',
            field=models.TextField(blank=True, default=b'', max_length=1000, null=True, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='program',
            name='fees',
            field=models.TextField(blank=True, default=b'', max_length=200, verbose_name='fees'),
        ),
        migrations.AlterField(
            model_name='program',
            name='fees_en',
            field=models.TextField(blank=True, default=b'', max_length=200, null=True, verbose_name='fees'),
        ),
        migrations.AlterField(
            model_name='program',
            name='fees_fr',
            field=models.TextField(blank=True, default=b'', max_length=200, null=True, verbose_name='fees'),
        ),
        migrations.AlterField(
            model_name='program',
            name='funding',
            field=models.TextField(blank=True, default=b'', max_length=200, verbose_name='funding'),
        ),
        migrations.AlterField(
            model_name='program',
            name='funding_en',
            field=models.TextField(blank=True, default=b'', max_length=200, null=True, verbose_name='funding'),
        ),
        migrations.AlterField(
            model_name='program',
            name='funding_fr',
            field=models.TextField(blank=True, default=b'', max_length=200, null=True, verbose_name='funding'),
        ),
        migrations.AlterField(
            model_name='program',
            name='length',
            field=models.TextField(blank=True, default=b'', max_length=200, verbose_name='length of the program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='length_en',
            field=models.TextField(blank=True, default=b'', max_length=200, null=True, verbose_name='length of the program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='length_fr',
            field=models.TextField(blank=True, default=b'', max_length=200, null=True, verbose_name='length of the program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='subsidies',
            field=models.TextField(blank=True, default=b'', max_length=200, verbose_name='subsidies'),
        ),
        migrations.AlterField(
            model_name='program',
            name='subsidies_en',
            field=models.TextField(blank=True, default=b'', max_length=200, null=True, verbose_name='subsidies'),
        ),
        migrations.AlterField(
            model_name='program',
            name='subsidies_fr',
            field=models.TextField(blank=True, default=b'', max_length=200, null=True, verbose_name='subsidies'),
        ),
        migrations.AlterField(
            model_name='program',
            name='support',
            field=models.TextField(blank=True, default=b'', max_length=200, verbose_name='support'),
        ),
        migrations.AlterField(
            model_name='program',
            name='support_en',
            field=models.TextField(blank=True, default=b'', max_length=200, null=True, verbose_name='support'),
        ),
        migrations.AlterField(
            model_name='program',
            name='support_fr',
            field=models.TextField(blank=True, default=b'', max_length=200, null=True, verbose_name='support'),
        ),
        migrations.AddField(
            model_name='programlinks',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osr.Program', verbose_name='program'),
        ),
        migrations.AddField(
            model_name='program',
            name='eligible_immigration_status',
            field=models.ManyToManyField(to='osr.ImmigrationStatus'),
        ),
        migrations.AddField(
            model_name='program',
            name='learning_options',
            field=models.ManyToManyField(to='osr.LearningOption'),
        ),
        migrations.AddField(
            model_name='program',
            name='schedule_options',
            field=models.ManyToManyField(to='osr.ScheduleOption'),
        ),
        migrations.AddField(
            model_name='program',
            name='types_of_service_providers',
            field=models.ManyToManyField(to='osr.ServiceProviderType'),
        ),
    ]
