# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0003_auto_20180403_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='has_access_computers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offering',
            name='has_access_kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offering',
            name='has_access_libraries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offering',
            name='has_access_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offering',
            name='has_access_wheelchair',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offering',
            name='has_childcare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offering',
            name='has_counselling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offering',
            name='has_employment',
            field=models.BooleanField(default=False),
        ),
    ]
