# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0004_auto_20180403_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='num_perks',
            field=models.SmallIntegerField(default=0),
        ),
    ]
