# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0004_auto_20180706_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='types_of_sps_en',
            field=models.TextField(blank=True, default=b'', max_length=600, null=True, verbose_name='types of service providers'),
        ),
        migrations.AddField(
            model_name='program',
            name='types_of_sps_fr',
            field=models.TextField(blank=True, default=b'', max_length=600, null=True, verbose_name='types of service providers'),
        ),
    ]
