# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0005_auto_20180706_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programbestforscenarios',
            name='text',
            field=models.CharField(max_length=300, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='programbestforscenarios',
            name='text_en',
            field=models.CharField(max_length=300, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='programbestforscenarios',
            name='text_fr',
            field=models.CharField(max_length=300, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='programregistrationsteps',
            name='text',
            field=models.CharField(max_length=300, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='programregistrationsteps',
            name='text_en',
            field=models.CharField(max_length=300, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='programregistrationsteps',
            name='text_fr',
            field=models.CharField(max_length=300, null=True, verbose_name='text'),
        ),
    ]
