# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0006_auto_20180706_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='text')),
                ('text_en', models.CharField(max_length=200, null=True, verbose_name='text')),
                ('text_fr', models.CharField(max_length=200, null=True, verbose_name='text')),
            ],
            options={
                'verbose_name': 'benefit',
                'verbose_name_plural': 'benefits',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='description_for_comparison_page',
            field=models.TextField(blank=True, default=b'', max_length=1000, verbose_name='description for comparison page'),
        ),
        migrations.AddField(
            model_name='program',
            name='description_for_comparison_page_en',
            field=models.TextField(blank=True, default=b'', max_length=1000, null=True, verbose_name='description for comparison page'),
        ),
        migrations.AddField(
            model_name='program',
            name='description_for_comparison_page_fr',
            field=models.TextField(blank=True, default=b'', max_length=1000, null=True, verbose_name='description for comparison page'),
        ),
        migrations.AddField(
            model_name='program',
            name='benefits',
            field=models.ManyToManyField(to='osr.Benefit'),
        ),
    ]
