# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0006_remove_offering_num_perks'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='code',
            field=models.CharField(default=b'pro', max_length=3),
        ),
    ]
