# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0007_auto_20180710_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='order_id',
            field=models.PositiveSmallIntegerField(default=1, help_text='a lower order id will show up first, min value is 1', verbose_name='order id'),
        ),
    ]
