# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0008_program_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('text', models.CharField(max_length=100, verbose_name='text')),
                ('order_id', models.PositiveSmallIntegerField(default=1, help_text='a lower order id will show up first, min value is 1', verbose_name='order id')),
                ('section', models.CharField(choices=[(b'Information', 'Information'), (b'Goals', 'Goals'), (b'Needs', 'Needs')], max_length=12, verbose_name='section in profile')),
            ],
            options={
                'verbose_name': 'profile information',
                'verbose_name_plural': 'profile information',
            },
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['order_id'], 'verbose_name': 'program', 'verbose_name_plural': 'programs'},
        ),
        migrations.AddField(
            model_name='recommendation',
            name='order_id',
            field=models.PositiveSmallIntegerField(default=1, help_text='a lower order id will show up first, min value is 1', verbose_name='order id'),
        ),
    ]
