# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0009_auto_20180729_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileInformation',
        ),
        migrations.RemoveField(
            model_name='program',
            name='img_src',
        ),
        migrations.RemoveField(
            model_name='program',
            name='img_txt',
        ),
    ]
