# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0011_profilesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesection',
            name='text_en',
            field=models.CharField(max_length=100, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='profilesection',
            name='text_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='text'),
        ),
    ]
