# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0012_auto_20180729_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilesection',
            options={'verbose_name': 'profile section', 'verbose_name_plural': 'profile sections'},
        ),
        migrations.AlterField(
            model_name='profilesection',
            name='code',
            field=models.CharField(max_length=100, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='code',
            field=models.CharField(max_length=100, verbose_name='code'),
        ),
    ]
