# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0013_auto_20180729_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilesection',
            options={'ordering': ['order_id'], 'verbose_name': 'profile section', 'verbose_name_plural': 'profile sections'},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['order_id'], 'verbose_name': 'recommendation', 'verbose_name_plural': 'recommendations'},
        ),
    ]
