# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0014_auto_20180729_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='text')),
                ('definition', models.CharField(max_length=500, verbose_name='text')),
            ],
            options={
                'verbose_name': 'dictionary entry',
                'verbose_name_plural': 'dictionary entries',
            },
        ),
    ]
