# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0015_dictionaryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryentry',
            name='definition_en',
            field=models.CharField(max_length=500, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='definition_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='key_en',
            field=models.CharField(max_length=100, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='key_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='text'),
        ),
    ]
