# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0016_auto_20180730_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='definition',
            field=models.CharField(max_length=500, verbose_name='definition'),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='definition_en',
            field=models.CharField(max_length=500, null=True, verbose_name='definition'),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='definition_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='definition'),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='key',
            field=models.CharField(max_length=100, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='key_en',
            field=models.CharField(max_length=100, null=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='key_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='key'),
        ),
    ]
