# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0017_auto_20180801_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_of_visit', models.CharField(max_length=50)),
                ('found_what_i_was_looking_for', models.CharField(max_length=10)),
                ('website_easy_to_navigate', models.CharField(max_length=10)),
                ('information_easy_to_understand', models.CharField(max_length=10)),
                ('matchmaker_easy_to_use', models.CharField(max_length=10)),
                ('matchmaker_helpful', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=50)),
                ('type_of_user', models.CharField(max_length=50)),
                ('most_useful_feature', models.CharField(max_length=50)),
                ('content_or_feature_request', models.CharField(max_length=2000)),
                ('general_comment', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedback',
            },
        ),
    ]
