# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0019_auto_20180801_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DictionaryEntry',
            new_name='GlossaryEntry',
        ),
        migrations.AlterModelOptions(
            name='glossaryentry',
            options={'verbose_name': 'glossary entry', 'verbose_name_plural': 'glossary entries'},
        ),
    ]
