# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0022_auto_20180801_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 17, 47, 46, 402450, tzinfo=utc), verbose_name='Timestamp'),
        ),
    ]
