# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osr', '0024_auto_20180801_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(default=b'2018-08-01 23:23:36', verbose_name='Timestamp'),
        ),
    ]
